services:
  ganglion:
    image: ghcr.io/ubaumann/cnpod_posting:main
    environment:
      - ACCOUNTS=pod-1;pod-2
    ports:
      - "8080:8080"
    command: ["sh", "-c", "python init.py && ganglion serve --config ganglion-local.toml"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    volumes:
      - account-keys:/data/.keys
      - sqlide-data:/data/db
    networks:
      - backend
  sw01-pod-1:
    image: "ghcr.io/ubaumann/cn_posting_collection:main"
    environment:
      - DEVICE=sw01-pod-1.network.garden
      - DEVICE_USER=${DEVICE_USER:-username}
      - DEVICE_PASSWORD=${DEVICE_PASSWORD:-password}
      - API_SERVER=ganglion:8080
      - APP_NAME=sw01
      - APP_ACCOUNT=pod-1
      - DECRYPTION_KEY=yJ3RNNOyeGc2NRVzR4PbwKf79_D9fQtlvCL7cIcXJKQ=
    depends_on:
      ganglion:
        condition: service_healthy
    volumes:
      - account-keys:/data/.keys
    networks:
      - backend
  sw02-pod-1:
    image: "ghcr.io/ubaumann/cn_posting_collection:main"
    environment:
      - DEVICE=sw02-pod-1.network.garden
      - DEVICE_USER=${DEVICE_USER:-username}
      - DEVICE_PASSWORD=${DEVICE_PASSWORD:-password}
      - API_SERVER=ganglion:8080
      - APP_NAME=sw02
      - APP_ACCOUNT=pod-1
      - DECRYPTION_KEY=yJ3RNNOyeGc2NRVzR4PbwKf79_D9fQtlvCL7cIcXJKQ=
    depends_on:
      ganglion:
        condition: service_healthy
    volumes:
      - account-keys:/data/.keys
    networks:
      - backend
  sw01-pod-2:
    image: "ghcr.io/ubaumann/cn_posting_collection:main"
    environment:
      - DEVICE=sw01-pod-2.network.garden
      - DEVICE_USER=${DEVICE_USER:-username}
      - DEVICE_PASSWORD=${DEVICE_PASSWORD:-password}
      - API_SERVER=ganglion:8080
      - APP_NAME=sw01
      - APP_ACCOUNT=pod-2
    depends_on:
      ganglion:
        condition: service_healthy
    volumes:
      - account-keys:/data/.keys
    networks:
      - backend

volumes:
  account-keys:
  sqlide-data:

networks:
  backend:
