---
namespace: cn-posting

pods:
  - pod-1
  - pod-2
  - pod-3
  - pod-4
  - pod-5
  - pod-6
  - pod-7
  - pod-8
  - pod-9
devices: ["sw01", "sw02", "sw03", "sw04", "rt01", "rt02" ]
device_mgmt_cidr: 10.8.40.0/24
device_username: admin
device_password: admin

ingress_fqdn: posting.stud.network.garden
ingress_https: true
ingress_wss: true

image_ganglion: ghcr.io/ubaumann/cnpod_posting:v0.1.3
image_posting: ghcr.io/ubaumann/cn_posting_collection:v0.1.2

# Used for encryption of API keys
crypto_key:  # "yJ3RNNOyeGc2NRVzR4PbwKf79_D9fQtlvCL7cIcXJKQ="  # Example key, replace with your own

# Use http GET instead shared file system for API keys
use_http_get: true

resources_requests_cpu_ganglion: 20m
resources_requests_memory_ganglion: 100Mi
resources_limits_cpu_ganglion: 250m
resources_limits_memory_ganglion: 400Mi

resources_requests_cpu_posting: 20m
resources_requests_memory_posting: 100Mi
resources_limits_cpu_posting: 250m
resources_limits_memory_posting: 400Mi
