[server]
# The base URL where ganglion serves from
base_url = "${HTTP_PROTOCOL}://${PUBLIC_URL}"
# The URL for applications
app_url_format = "${HTTP_PROTOCOL}://${PUBLIC_URL}/{account}/{application}"
# The websocket URL where applications are served from
app_websocket_url = "${WS_PROTOCOL}://${PUBLIC_URL}"

[templates]
# Root directory for templates
root = "${GANGLION_DATA}/templates"

[static]
# Local directory where static assets are contained
root = "${GANGLION_DATA}/static"
# URL where static assets are served from
url = "/static/"

[db]
# sqlalchemy async database URL
url = "sqlite+aiosqlite:///./db/ganglion.db"
# Consider Postgres for production
#url = "postgresql+asyncpg://postgres:password@localhost/ganglion"
