{{- range $i, $pod := $.Values.pods }}
{{- range $.Values.devices }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: device-{{ . }}-{{ $pod }}
  namespace: {{ $.Values.namespace }}
data:
  hostname: "{{ . }}-pod-{{ $pod }}.network.garden"
{{- end }}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: device-secret
  namespace: {{ $.Values.namespace }}
stringData:
  username: "admin"
  password: "admin"