---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ganglion-accounts
  namespace: {{ $.Values.namespace }}
data:
  accounts: {{ $.Values.pods | join ";" }}
{{- range $i, $pod := $.Values.pods }}
{{- range $.Values.devices }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: device-{{ . }}-{{ $pod }}
  namespace: {{ $.Values.namespace }}
data:
  hostname: "{{ . }}-pod-{{ $pod }}.network.garden"
{{- end }}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: device-secret
  namespace: {{ $.Values.namespace }}
stringData:
  username: "{{ $.Values.device_username }}"
  password: "{{ $.Values.device_password }}"
{{ if $.Values.crypto_key }}
---
apiVersion: v1
kind: Secret
metadata:
  name: ganglion-crypto_key-secret
  namespace: {{ $.Values.namespace }}
stringData:
  key: "{{ $.Values.crypto_key }}"
{{ end }}