---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ganglion
  namespace: {{ $.Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ganglion
  template:
    metadata:
      labels:
        app: ganglion
    spec:
      initContainers:
        - name: ganglion-init
          image: {{ $.Values.image_ganglion }}
          command: ["python", "init.py"]
          volumeMounts:
            - name: ganglion-token-vol
              mountPath: /mnt/token
      containers:
        - name: ganglion
          image: {{ $.Values.image_ganglion }}
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: {{ $.Values.resources_requests_cpu_ganglion }}
              memory: {{ $.Values.resources_requests_memory_ganglion }}
            limits:
              cpu: {{ $.Values.resources_limits_cpu_ganglion }}
              memory: {{ $.Values.resources_limits_memory_ganglion }}
{{- range $i, $pod := $.Values.pods }}
{{- range $.Values.devices }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: posting-{{ . }}-{{ $pod }}
  namespace: {{ $.Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: posting-{{ . }}-{{ $pod }}
  template:
    metadata:
      labels:
        app: posting-{{ . }}-{{ $pod }}
    spec:
      containers:
        - name: poster
          image: {{ $.Values.image_posting }}
          resources:
            requests:
              cpu: {{ $.Values.resources_requests_cpu_posting }}
              memory: {{ $.Values.resources_requests_memory_posting }}
            limits:
              cpu: {{ $.Values.resources_limits_cpu_posting }}
              memory: {{ $.Values.resources_limits_memory_posting }}
          env:
            - name: DEVICE_USER
              valueFrom:
                secretKeyRef:
                  name: device-secret
                  key: username
            - name: DEVICE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: device-secret
                  key: password
            - name: DEVICE
              valueFrom:
                configMapKeyRef:
                  name: device-{{ . }}-{{ $pod }}
                  key: hostname
          volumeMounts:
            - name: ganglion-token-vol
              mountPath: /mnt/token
{{- end }}
{{- end }}