---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ganglion
  namespace: {{ $.Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ganglion
  template:
    metadata:
      labels:
        app: ganglion
    spec:
      initContainers:
        - name: ganglion-init
          image: {{ $.Values.image_ganglion }}
          command: ["python", "init.py"]
          env:
            - name: ACCOUNTS
              valueFrom:
                configMapKeyRef:
                  name: ganglion-accounts
                  key: accounts
{{- if $.Values.crypto_key }}
            - name: ENCRYPTION_KEY
              valueFrom:
                secretKeyRef:
                  name: ganglion-crypto-key-secret
                  key: key
{{- end }}
          resources:
            requests:
              cpu: {{ $.Values.resources_requests_cpu_ganglion }}
              memory: {{ $.Values.resources_requests_memory_ganglion }}
            limits:
              cpu: {{ $.Values.resources_limits_cpu_ganglion }}
              memory: {{ $.Values.resources_limits_memory_ganglion }}
          volumeMounts:
            - name: ganglion-token-vol
              mountPath: /data/.keys
            - name: ganglion-sqlite-vol
              mountPath: /data/db
      containers:
        - name: ganglion
          image: {{ $.Values.image_ganglion }}
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: {{ $.Values.resources_requests_cpu_ganglion }}
              memory: {{ $.Values.resources_requests_memory_ganglion }}
            limits:
              cpu: {{ $.Values.resources_limits_cpu_ganglion }}
              memory: {{ $.Values.resources_limits_memory_ganglion }}
          volumeMounts:
            - name: ganglion-sqlite-vol
              mountPath: /data/db
{{- if $.Values.use_http_get}}
        - name: ganglion-serve-http-key
          image: python:3.13
          workingDir: "/data/.keys"
          command: ["python", "-m", "http.server"]
          ports:
            - containerPort: 8000
          resources:
            requests:
              cpu: {{ $.Values.resources_requests_cpu_ganglion }}
              memory: {{ $.Values.resources_requests_memory_ganglion }}
            limits:
              cpu: {{ $.Values.resources_limits_cpu_ganglion }}
              memory: {{ $.Values.resources_limits_memory_ganglion }}
          volumeMounts:
            - name: ganglion-token-vol
              mountPath: /data/.keys
{{- end }}
      volumes:
        - name: ganglion-token-vol
          persistentVolumeClaim:
            claimName: ganglion-token-pvc
        - name: ganglion-sqlite-vol
          persistentVolumeClaim:
            claimName: ganglion-sqlite-pvc
          
{{- range $i, $pod := $.Values.pods }}
{{- range $.Values.devices }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: posting-{{ . }}-{{ $pod }}
  namespace: {{ $.Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: posting-{{ . }}-{{ $pod }}
  template:
    metadata:
      labels:
        app: posting-{{ . }}-{{ $pod }}
    spec:
      containers:
        - name: poster
          image: {{ $.Values.image_posting }}
          resources:
            requests:
              cpu: {{ $.Values.resources_requests_cpu_posting }}
              memory: {{ $.Values.resources_requests_memory_posting }}
            limits:
              cpu: {{ $.Values.resources_limits_cpu_posting }}
              memory: {{ $.Values.resources_limits_memory_posting }}
          env:
            - name: DEVICE_USER
              valueFrom:
                secretKeyRef:
                  name: device-secret
                  key: username
            - name: DEVICE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: device-secret
                  key: password
            - name: DEVICE
              valueFrom:
                configMapKeyRef:
                  name: device-{{ . }}-{{ $pod }}
                  key: hostname
            - name: APP_NAME
              value: {{ . }}
            - name: APP_ACCOUNT
              value: {{ $pod }}
            - name: API_SERVER
              value: ganglion:80
{{- if $.Values.use_http_get}}
            - name: KEY_LOCATION
              value: "http://ganglion:8000"
{{- end }}
{{- if $.Values.crypto_key }}
            - name: DECRYPTION_KEY
              valueFrom:
                secretKeyRef:
                  name: ganglion-crypto-key-secret
                  key: key
{{- end }}
{{- if not $.Values.use_http_get}}
          volumeMounts:
            - name: ganglion-token-vol
              mountPath: /data/.keys
              readOnly: true
      volumes:
        - name: ganglion-token-vol
          persistentVolumeClaim:
            claimName: ganglion-token-pvc
{{- end }}
{{- end }}
{{- end }}