apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: posting
  namespace: cn-posting
spec:
  ingressClassName: nginx
  rules:
    - host: posting.stud.network.garden
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: ganglion
                port:
                  name: web
