apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: posting
  namespace: {{ $.Values.namespace }}
spec:
  ingressClassName: nginx
  rules:
    - host: {{ $.Values.ingress_fqdn}}
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: ganglion
                port:
                  name: web
