apiVersion: v1
kind: Service
metadata:
  labels:
    app: ganglion
  name: ganglion
  namespace: cn-posting
spec:
  ports:
  - name: web
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: ganglion
  type: ClusterIP
