apiVersion: v1
kind: Service
metadata:
  labels:
    app: ganglion
  name: ganglion
  namespace: {{ $.Values.namespace }}
spec:
  ports:
  - name: web
    port: 80
    protocol: TCP
    targetPort: 8080
{{- if $.Values.use_http_get}}
  - name: tokens
    port: 8000
    protocol: TCP
    targetPort: 8000
{{- end }}
  selector:
    app: ganglion
  type: ClusterIP
