name: Build and Push Helm Chart

on:
  push:
    tags:
      - v**
  workflow_dispatch:

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    # Sets the permissions granted to the `GITHUB_TOKEN` for the actions in this job.
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Helm
        uses: azure/setup-helm@v4.3.0

      - name: Helm Registry Login
        run: helm registry login ghcr.io --username ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN }}

      - name: Helm Package
        run: helm package . --app-version=${{ github.ref_name }}

      - name: Helm Push
        run: helm push *.tgz oci://ghcr.io/${{ github.repository }}
